global:
  resolve_timeout: 1m

route:
  group_by: ['alerts']                                    
  group_wait: 2m                                             # Time to wait before sending first notification.
  group_interval: 5m                                         # Time to wait before sending notification for new alerts of same type, when first notification is already sent.
  receiver: 'email-notification'                             # Receiver group name.

receivers:                                                   # List of notification receivers.
  - name: 'email-notification'
    email_configs:
      - to: email-address                            
        from: email-address 
        smarthost: smtp.gmail.com:587                        # The SMTP host through which emails are sent.
        auth_username: email-address 
        auth_identity: email-address 
        auth_password: password
        send_resolved: true                                   # When alert is resolved, another email is triggered.